### ISSUE TITLE
How do you apply this?

### ISSUE THREAD

**Issue by foreck** [Andrewthedev/TECLIT#2]
Hi! Does this code actually work? How do you apply this and make it work? Do you need the Netbeans IDE to activate this code? 
Thanks for your hard work!

**Comment by Andrewthedev** [comment]
You will need the JRE which can be found here : [Java](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html)

If you want to build the code yourself you can load it into netbeans and hit build and it will work. (which might be a nightmare because this code is some hot garbage :P )

SO, to make things easy I put up a link on my google drive with the project already built for you. [TEC-Lit](https://drive.google.com/open?id=0B5wfwdv1ddoBZTNaV1FrUFZrVnM)

There is a scripts/logs/macros folder. I left a template for a script in there if you want to see how it works. The first line should always be the weapon you are using (for fumble recovery) followed by a list of you rotation. The logs folder will automatically populate when you start the application, and the macros will take each line in the macros folder and create a little window (it looks ugly btw).

**Comment by Andrewthedev** [comment]
If you want to contact me via skype I can walk you through the small little features that this client has.  My skype name is ffxisancin.

Also you will want to leave everything in the folder after you unzip it and run the ExternalCityFXML.jar to start the client.

Also, it should look like this.

![image](https://user-images.githubusercontent.com/10337752/28571378-969b608a-7110-11e7-92a0-94c020176c53.png)

**Comment by foreck** [comment]
Awesome! I did download netbeans and the JDK to try and get it to run. When
I hit build, it just fails and does nothing. Im going to grab it off your
google drive and try it that way. Im headed to class here in a little bit
so I dont know what I can get done. Thank you for your hard work!

**Comment by foreck** [comment]
Holy crap batman it works. The JAR file loaded right up. You are amazing!!

**Comment by foreck** [comment]
I am having trouble with the scripts.  In your example it looks like you
are using macros and the @target command to fully use the three letter
commands.  I tried duplicating this by setting a macro in the game to
attack=attack <target>.
I think made a separate notepad file titled staves.txt. in it,  I simply
typed attack.

When I activate the scripts using the top control bar,  it seems to do
nothing,  and then freezes.
When I select the script staves.txt, and press start at the bottom of your
client,  the client freezes.

Any advice as to what im messing up?

Thanks!

**Comment by Andrewthedev** [comment]
Oh sorry! Yes, I use macros so for each line of the script file I have a command that I have macro'd to 

command <target>

Also, to start the script you will want to click on the script in the list box you want to activate and click on the "start" button. The "load script list" is if you add a new script to the folder and you want to repopulate the script list. The stop button will stop any script that is running. Also, the light theme button must be unchecked before logging into TEC in order for it to work (needs fixed for sure).

**Comment by Andrewthedev** [comment]
Do you have Skype? I can help you out on there.

**Comment by foreck** [comment]
I think I have skype.  Im actually not sure.  I know my wife video chats
with her mom,  but who knows.
Ill try and use the scripts again tonight.
Do they just spam over and over,  or is there a trigger to make them work?

I really appreciate you,  you are freaking awesome!

**Comment by Andrewthedev** [comment]
Nah, they spam over and over until you stop the script ;)

**Comment by foreck** [comment]
I figure no big deal really then.  I mean,  when im trying to watch deep
space 9, its distracting to be at the courses and keep clicking each macro
button :)

**Comment by Andrewthedev** [comment]
Oh btw the client has a built in script for the 3 and 4 parter. Just go to the courses and do the first action and it'll automatically kick off

**Comment by foreck** [comment]
So ive been using it almost a month and I absolutely love it. Its made
playing the repetitive stuff FUN. You are amazing.

I started looking up how to code in Java, because I had an idea for
scripting pickpocketing, similar to how you run the combat script.

I copied the fxml and put it into a new folder, and in that folder I
extracted it. I turned on netbeans, and when I access it (Which I can only
do by dragging and dropping it on to netbeans) it comes up a weird format
that is read only. Should I go back to your github one and pull that one to
try and add code?

Ben

**Comment by Andrewthedev** [comment]
Yeah so.. You will need a few things. First you'll want to pull the code from here. Once you do that in netbeans you should be able to open a new project with file -> open project.

Once the project is open you will get warnings about missing libraries. The libraries you will need are in the /libs folder. To add them you right click on the main project go to properties then click Libraries in the tree. Once you are in the add library part you will want to click on Add Jar/folder. Unzipping the files in the /lib directory will contain the jars you will need.

Once that is complete you will want to get JavaFX scene builder and then you should be good to go on development.
